config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  
  root 'static_pages#home'
  resources :microposts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about' 
  get 'static_pages/contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order(created_at: :desc) }
	mount_uploader :picture, PictureUploader
	validates :user_id, presence: true
	 validates :content, presence: true, length: { maximum: 140 }
	 validate  :picture_size

	 private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :correct_user,   only: :destroy
	
	def new
		@micropost= Micropost.new
	end

	def create
		@micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
    	@feed_items = []
      render 'static_pages/home'
    end
    	end

	def index
		@micropost=Micropost.all
	end

	def edit
		@micropost=Micropost.find_by(id:params[:id])
	end

	def update
		@micropost=Micropost.find_by(id:params[:id])
		if @micropost.update_attributes(content:params[:micropost][:content], user_id:params[:micropost][:user_id])
			redirect_to microposts_path
		else
			redirect_to microposts_path
		end
	end

	def destroy
		@micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
	end

	def show
		@micropost=Micropost.find_by(id:params[:id])
	end

private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/edit.html.erb
<h1>New Micropost</h1>
<%=form_for @micropost do |f|%>
	<%=f.label :content%>
	<%=f.text_area :content%>
	<br>
	User Id<%=f.select :user_id, options_for_select(User.pluck(:id)), prompt: "-Select Id-"%>
	<br>
	<%=f.submit "Update"%>
<%end%>
<br>
<%=link_to "BACK", :back%>

app/views/microposts/index.html.erb
<h1>Listing Microposts</h1>
<table>
	<tr>
		<th>Content</th>
		<th>User Id</th>
	</tr>
	<%@micropost.each do |micropost|%>
		<tr>
			<td><%=micropost.content%></td>
			<td><%=micropost.user_id%></td>
			<td><%=link_to "show", micropost_path(micropost.id)%>
			<td><%=link_to "edit", edit_micropost_path(micropost.id)%>
			<td><%=link_to "delete", micropost_path(micropost.id), method: :DELETE, data: {confirm:"Are you sure you want to DELETE it???"}%>
		</tr>
	<%end%>	
	<br>
</table>
<br>
<%=link_to "New Micropost", new_micropost_path%>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>
<%=form_for @micropost do |f|%>
	<%=f.label :content%>
	<%=f.text_area :content%>
	<br>
	User Id<%=f.select :user_id, options_for_select(User.pluck(:id)), prompt: "-Select Id-"%>
	<br>
	<%=f.submit "Create "%>
<%end%>
<br>
<%=link_to "BACK", :back%>

app/views/microposts/show.html.erb
Micropost was successfully created...
<br>
Content: <%=@micropost.content%>
<br>
Id: <%=@micropost.user_id%>
<br>
<%=link_to "Edit", edit_micropost_path(@micropost)%>  |
<%=link_to "All Microposts", microposts_path%>  |
<%=link_to "Back", :back%>